### ISSUE TITLE
AWS_SDK_LOAD_CONFIG required without ~/.aws/credentials file

### ISSUE THREAD

**Issue by JRemitz** [joeledwards/node-aws#1]
Hey @joeledwards!  I have had issues getting this to work with AWS SSO however I've finally been able to by reversing the recommendation to unset `AWS_SDK_LOAD_CONFIG`.  My observations:

1. If  I have a `~/.aws/credentials` file with creds in it, leaving `AWS_SDK_LOAD_CONFIG` unset works
2. If I have either commented out everything in `~/.aws/credentials` or removed the file entirely, I need to have `AWS_SDK_LOAD_CONFIG` set (used value of `1`) and it works.  Otherwise I get an error with `BUZULI_AWS_VERBOSE=true` where it appears that `SSOOIDC` appears to be trying to retrieve EC2 instance metadata.
    ```
    ...
    Fatal: Error: Failed to resolve AWS credentials. Did you set the AWS_PROFILE environment variable?
    ...
      cause: Error [TimeoutError]: EC2 Metadata roleName request returned error
    ...
    ```
    This _seems_ to align with the [AWS Documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-configured-credential-process.html) but maybe I'm misunderstanding something or have something else misconfigured?

Thanks!

**Comment by joeledwards** [comment]
Hi @JRemitz! Sorry to hear you are running into issues with this. Do you have a profile named `default` in `~/.aws/config`? You can specify which profile to use via `AWS_PROFILE`.

I thought I had a provider chain that would work cleanly. It shouldn't reach that final attempt to pull EC2 metadata until after all other approaches have been attempted (pulling from profiles, pulling from credentials, etc.).

**Comment by joeledwards** [comment]
https://github.com/joeledwards/node-aws/blob/cf83a560396575b7d1be1e4a6009156a4ea3b4ae/lib/auth/index.js#L13

I just pushed my new SSO provider to the front of the default chain, so it should fallback to other methods only if it is unable to resolve via the SSO provider. The above error then appears only if you "fall off" the end of the provider chain without finding a valid auth mechanism.

**Comment by joeledwards** [comment]
This is the line on the README
https://github.com/joeledwards/node-aws/blob/cf83a560396575b7d1be1e4a6009156a4ea3b4ae/README.md?plain=1#L38

That looks wrong to me, I will have to update it. I do not have a credentials file and have `AWS_SDK_LOAD_CONFIG=true` in my shell and it is working without issue.

**Comment by joeledwards** [comment]
Alright, that is corrected. Sorry for the confusion ☹️

**Comment by JRemitz** [comment]
Amazing, thanks Joel!
